name: Android CI (Build APK)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Rebuild structure
        run: bash rebuild_structure.sh

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Debug APK
        run: ./gradlew clean :app:assembleDebug

      - name: Build Release APK
        run: ./gradlew :app:assembleRelease

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: slots-apks
          path: |
            app/build/outputs/apk/debug/app-debug.apk
            app/build/outputs/apk/release/app-release.apk
